# Generated by Django 5.0.3 on 2024-05-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assign_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsetmodel",
            name="Has_backside",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default=3, max_length=5
            ),
            preserve_default=False,
        ),
    ]
